name: Check Markdown Files for unformatted pollutants

on: [push, pull_request]

jobs:
  check-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Run markdown files check
        run: node ./scripts/pollutant-names.js ./docs

      - name: Fail the job if any string is found
        if: failure()
        run: echo "One or more specified strings were found in the markdown files. Failing the job."